In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("C:/Users/chand/OneDrive/Documents/Desktop/python_pandas/Superstore sales dataset.csv")

In [4]:
df.shape

(9994, 21)

In [5]:
df.head

<bound method NDFrame.head of       Row ID        Order ID  Order Date   Ship Date       Ship Mode  \
0          1  CA-2016-152156   8/11/2016  11/11/2016    Second Class
1          2  CA-2016-152156   8/11/2016  11/11/2016    Second Class
2          3  CA-2016-138688   12/6/2016   16/6/2016    Second Class
3          4  US-2015-108966  11/10/2015  18/10/2015  Standard Class
4          5  US-2015-108966  11/10/2015  18/10/2015  Standard Class
...      ...             ...         ...         ...             ...
9989    9990  CA-2014-110422   21/1/2014   23/1/2014    Second Class
9990    9991  CA-2017-121258   26/2/2017    3/3/2017  Standard Class
9991    9992  CA-2017-121258   26/2/2017    3/3/2017  Standard Class
9992    9993  CA-2017-121258   26/2/2017    3/3/2017  Standard Class
9993    9994  CA-2017-119914    4/5/2017    9/5/2017    Second Class

     Customer ID     Customer Name    Segment        Country             City  \
0       CG-12520       Claire Gute   Consumer  United States        Henderson
1       CG-12520       Claire Gute   Consumer  United States        Henderson
2       DV-13045   Darrin Van Huff  Corporate  United States      Los Angeles
3       SO-20335    Sean O'Donnell   Consumer  United States  Fort Lauderdale
4       SO-20335    Sean O'Donnell   Consumer  United States  Fort Lauderdale
...          ...               ...        ...            ...              ...
9989    TB-21400  Tom Boeckenhauer   Consumer  United States            Miami
9990    DB-13060       Dave Brooks   Consumer  United States       Costa Mesa
9991    DB-13060       Dave Brooks   Consumer  United States       Costa Mesa
9992    DB-13060       Dave Brooks   Consumer  United States       Costa Mesa
9993    CC-12220      Chris Cortes   Consumer  United States      Westminster

      ... Postal Code  Region       Product ID         Category Sub-Category  \
0     ...       42420   South  FUR-BO-10001798        Furniture    Bookcases
1     ...       42420   South  FUR-CH-10000454        Furniture       Chairs
2     ...       90036    West  OFF-LA-10000240  Office Supplies       Labels
3     ...       33311   South  FUR-TA-10000577        Furniture       Tables
4     ...       33311   South  OFF-ST-10000760  Office Supplies      Storage
...   ...         ...     ...              ...              ...          ...
9989  ...       33180   South  FUR-FU-10001889        Furniture  Furnishings
9990  ...       92627    West  FUR-FU-10000747        Furniture  Furnishings
9991  ...       92627    West  TEC-PH-10003645       Technology       Phones
9992  ...       92627    West  OFF-PA-10004041  Office Supplies        Paper
9993  ...       92683    West  OFF-AP-10002684  Office Supplies   Appliances

                                           Product Name     Sales  Quantity  \
0                     Bush Somerset Collection Bookcase  261.9600         2
1     Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400         3
2     Self-Adhesive Address Labels for Typewriters b...   14.6200         2
3         Bretford CR4500 Series Slim Rectangular Table  957.5775         5
4                        Eldon Fold 'N Roll Cart System   22.3680         2
...                                                 ...       ...       ...
9989                             Ultra Door Pull Handle   25.2480         3
9990  Tenex B1-RE Series Chair Mats for Low Pile Car...   91.9600         2
9991                              Aastra 57i VoIP phone  258.5760         2
9992  It's Hot Message Books with Stickers, 2 3/4" x 5"   29.6000         4
9993  Acco 7-Outlet Masterpiece Power Center, Wihtou...  243.1600         2

      Discount    Profit
0         0.00   41.9136
1         0.00  219.5820
2         0.00    6.8714
3         0.45 -383.0310
4         0.20    2.5164
...        ...       ...
9989      0.20    4.1028
9990      0.00   15.6332
9991      0.20   19.3932
9992      0.00   13.3200
9993      0.00   72.9480

[9994 rows x 21 columns]>

In [6]:
df.head(2)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,8/11/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.0,41.9136
1,2,CA-2016-152156,8/11/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.0,219.5820

In [7]:
import pandas as pd

In [8]:
pd.DataFrame([1,2,3],columns=['A'],index=['A','B','C'])

   A
A  1
B  2
C  3

In [9]:
pd.DataFrame((1,2,3))

   0
0  1
1  2
2  3

In [10]:
pd.DataFrame({"months":["jan","feb"],"sales":[20,40]})

  months  sales
0    jan     20
1    feb     40

In [11]:
import numpy as np
np.random.seed(121)
df=pd.DataFrame(np.random.randint(0,10,(3,3)))

In [12]:
df

   0  1  2
0  2  5  8
1  4  1  4
2  3  0  2

In [13]:
np.random.seed(121)
df=pd.DataFrame(np.random.randint(0,10,(3,3)),columns="A B C".split(),index='P Q R'.split())
df

   A  B  C
P  2  5  8
Q  4  1  4
R  3  0  2

In [14]:
df

   A  B  C
P  2  5  8
Q  4  1  4
R  3  0  2

In [15]:
import pandas as pd
df=pd.read_csv("C:/Users/chand/Downloads/Superstore sales dataset.csv")

In [16]:
df.shape

(9994, 21)

In [17]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [18]:
df.head(2)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,8/11/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.0,41.9136
1,2,CA-2016-152156,8/11/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.0,219.5820

In [19]:
df.tail(2)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
9992,9993,CA-2017-121258,26/2/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.60,4,0.0,13.320
9993,9994,CA-2017-119914,4/5/2017,9/5/2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.16,2,0.0,72.948

In [20]:
df.index

RangeIndex(start=0, stop=9994, step=1)

In [21]:
df[['Row ID','Order ID','Sales']].head(2)

   Row ID        Order ID   Sales
0       1  CA-2016-152156  261.96
1       2  CA-2016-152156  731.94

In [22]:
df.iloc[2:8,[2,5,7]]

   Order Date Customer ID    Segment
2   12/6/2016    DV-13045  Corporate
3  11/10/2015    SO-20335   Consumer
4  11/10/2015    SO-20335   Consumer
5    9/6/2014    BH-11710   Consumer
6    9/6/2014    BH-11710   Consumer
7    9/6/2014    BH-11710   Consumer

In [23]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [24]:
df.dtypes

Row ID             int64
Order ID          object
Order Date        object
Ship Date         object
Ship Mode         object
Customer ID       object
Customer Name     object
Segment           object
Country           object
City              object
State             object
Postal Code        int64
Region            object
Product ID        object
Category          object
Sub-Category      object
Product Name      object
Sales            float64
Quantity           int64
Discount         float64
Profit           float64
dtype: object

In [25]:
np.iinfo(np.int8)

iinfo(min=-128, max=127, dtype=int8)

In [26]:
np.iinfo(np.int64)

iinfo(min=-9223372036854775808, max=9223372036854775807, dtype=int64)

In [27]:
np.finfo(np.float16).min

np.float16(-6.55e+04)

In [28]:
df.select_dtypes(include=['int64','float64']).head(2)

   Row ID  Postal Code   Sales  Quantity  Discount    Profit
0       1        42420  261.96         2       0.0   41.9136
1       2        42420  731.94         3       0.0  219.5820

In [29]:
df.shape

(9994, 21)

In [30]:
subset_df=df.iloc[0:5,0:5].copy()

In [31]:
subset_df

   Row ID        Order ID  Order Date   Ship Date       Ship Mode
0       1  CA-2016-152156   8/11/2016  11/11/2016    Second Class
1       2  CA-2016-152156   8/11/2016  11/11/2016    Second Class
2       3  CA-2016-138688   12/6/2016   16/6/2016    Second Class
3       4  US-2015-108966  11/10/2015  18/10/2015  Standard Class
4       5  US-2015-108966  11/10/2015  18/10/2015  Standard Class

In [32]:
subset_df[['Row ID','Order ID','Ship Mode','Ship Date']].min()

Row ID                    1
Order ID     CA-2016-138688
Ship Mode      Second Class
Ship Date        11/11/2016
dtype: object

In [33]:
df[['Sales']].mean()

Sales    229.858001
dtype: float64

In [34]:
df['Ship Mode'].str.upper().head(2)

0    SECOND CLASS
1    SECOND CLASS
Name: Ship Mode, dtype: object

In [35]:
df['Ship Mode'].str.lower().head(2)

0    second class
1    second class
Name: Ship Mode, dtype: object

In [36]:
df['Ship Mode'].str.capitalize().head(2)

0    Second class
1    Second class
Name: Ship Mode, dtype: object

In [37]:
df['Ship Mode'].str.title().head(2)

0    Second Class
1    Second Class
Name: Ship Mode, dtype: object

In [38]:
df['Ship Mode'].str.len().head(2)

0    12
1    12
Name: Ship Mode, dtype: int64

In [39]:
df['Ship Mode'].str.len().tail(2)

9992    14
9993    12
Name: Ship Mode, dtype: int64

In [40]:
df['Ship Mode'].str.strip().head(2)

0    Second Class
1    Second Class
Name: Ship Mode, dtype: object

In [41]:
"  data ".strip()

'data'

In [42]:
df['Ship Mode'].str.lstrip().head(2)

0    Second Class
1    Second Class
Name: Ship Mode, dtype: object

In [43]:
df['Ship Mode'].str.rstrip().head(2)

0    Second Class
1    Second Class
Name: Ship Mode, dtype: object

In [44]:
df['Ship Mode'].str.split(" ").str[0]

0         Second
1         Second
2         Second
3       Standard
4       Standard
          ...
9989      Second
9990    Standard
9991    Standard
9992    Standard
9993      Second
Name: Ship Mode, Length: 9994, dtype: object

In [45]:
"data science".split("a")

['d', 't', ' science']

In [46]:
df['Ship Mode'].str.pad(width=20,side='left',fillchar="-")

0       --------Second Class
1       --------Second Class
2       --------Second Class
3       ------Standard Class
4       ------Standard Class
                ...
9989    --------Second Class
9990    ------Standard Class
9991    ------Standard Class
9992    ------Standard Class
9993    --------Second Class
Name: Ship Mode, Length: 9994, dtype: object

In [47]:
df['Ship Mode'].str.count("Second")

0       1
1       1
2       1
3       0
4       0
       ..
9989    1
9990    0
9991    0
9992    0
9993    1
Name: Ship Mode, Length: 9994, dtype: int64

In [49]:
df.shape

(9994, 21)