In [65]:
import pandas as pd
import numpy as np

# Retail Dataset
data = {
    "Order_ID": ["CA-1001", "CA-1002", "CA-1003", "CA-1004"],
    "Customer_Name": ["John", np.nan, "David", "Maria"],
    "Region": ["South", "East", np.nan, "West"],
    "Category": ["Furniture", "Technology", "Office Supplies", np.nan],
    "Sales": [2500, np.nan, 1800, 3200],
    "Profit": [200, 350, np.nan, 500],
    "Discount": [0.10, np.nan, 0.20, 0.15],
    "Quantity": [2, 3, np.nan, 5]
}

In [66]:
df1 = pd.DataFrame(data)

In [67]:
df1

,Order_ID,Customer_Name,Region,Category,Sales,Profit,Discount,Quantity
0,CA-1001,John,South,Furniture,2500.0,200.0,0.10,2.0
1,CA-1002,NaN,East,Technology,NaN,350.0,NaN,3.0
2,CA-1003,David,NaN,Office Supplies,1800.0,NaN,0.20,NaN
3,CA-1004,Maria,West,NaN,3200.0,500.0,0.15,5.0

In [68]:
df1.shape

(4, 8)

In [69]:
(df1.isna().sum())

Order_ID         0
Customer_Name    1
Region           1
Category         1
Sales            1
Profit           1
Discount         1
Quantity         1
dtype: int64

In [71]:
a = (df1.isna().sum()/len(df1))*100

In [72]:
a

Order_ID          0.0
Customer_Name    25.0
Region           25.0
Category         25.0
Sales            25.0
Profit           25.0
Discount         25.0
Quantity         25.0
dtype: float64

## FILL NA

In [73]:
## fill na

df1['sales'] = df1['Sales'].fillna(df1['Sales'].mean())

In [74]:
df1['sales']

0    2500.0
1    2500.0
2    1800.0
3    3200.0
Name: sales, dtype: float64

In [75]:
df1

,Order_ID,Customer_Name,Region,Category,Sales,Profit,Discount,Quantity,sales
0,CA-1001,John,South,Furniture,2500.0,200.0,0.10,2.0,2500.0
1,CA-1002,NaN,East,Technology,NaN,350.0,NaN,3.0,2500.0
2,CA-1003,David,NaN,Office Supplies,1800.0,NaN,0.20,NaN,1800.0
3,CA-1004,Maria,West,NaN,3200.0,500.0,0.15,5.0,3200.0

In [76]:
df1['sales'].mean()

np.float64(2500.0)

In [77]:
df1.columns

Index(['Order_ID', 'Customer_Name', 'Region', 'Category', 'Sales', 'Profit',
       'Discount', 'Quantity', 'sales'],
      dtype='object')

In [78]:
df1['Discount'].mode()

0    0.10
1    0.15
2    0.20
Name: Discount, dtype: float64

In [79]:
df1['Profit'].mode()

0    200.0
1    350.0
2    500.0
Name: Profit, dtype: float64

In [80]:
df1['Quantity'].mean()

np.float64(3.3333333333333335)

In [81]:
df1.columns

Index(['Order_ID', 'Customer_Name', 'Region', 'Category', 'Sales', 'Profit',
       'Discount', 'Quantity', 'sales'],
      dtype='object')

In [82]:
df1['Sales']

0    2500.0
1       NaN
2    1800.0
3    3200.0
Name: Sales, dtype: float64

In [48]:
df1.shape

(4, 9)

In [88]:
df1['Discount']

0    2.0
1    3.0
2    NaN
3    5.0
Name: Discount, dtype: float64

## DROPNA

In [1]:
import pandas as pd
import numpy as np

# Retail Dataset
data = {
    "Order_ID": ["CA-1001", "CA-1002", "CA-1003", "CA-1004"],
    "Customer_Name": ["John", np.nan, "David", "Maria"],
    "Region": ["South", "East", np.nan, "West"],
    "Category": ["Furniture", "Technology", "Office Supplies", np.nan],
    "Sales": [2500, np.nan, 1800, 3200],
    "Profit": [200, 350, np.nan, 500],
    "Discount": [0.10, np.nan, 0.20, 0.15],
    "Quantity": [2, 3, np.nan, 5]
}

In [2]:
df2 = pd.DataFrame(data)

In [3]:
df2

,Order_ID,Customer_Name,Region,Category,Sales,Profit,Discount,Quantity
0,CA-1001,John,South,Furniture,2500.0,200.0,0.10,2.0
1,CA-1002,NaN,East,Technology,NaN,350.0,NaN,3.0
2,CA-1003,David,NaN,Office Supplies,1800.0,NaN,0.20,NaN
3,CA-1004,Maria,West,NaN,3200.0,500.0,0.15,5.0

In [8]:
df2.shape

(4, 8)

In [4]:
a1 = (df2.isna().sum()/len(df2))*100

In [5]:
a1

Order_ID          0.0
Customer_Name    25.0
Region           25.0
Category         25.0
Sales            25.0
Profit           25.0
Discount         25.0
Quantity         25.0
dtype: float64

## axis=1 means it works on columns level

In [10]:
df2.dropna(how='any',axis=1)

  Order_ID
0  CA-1001
1  CA-1002
2  CA-1003
3  CA-1004

In [11]:
df2.dropna(how='all',axis=1)

,Order_ID,Customer_Name,Region,Category,Sales,Profit,Discount,Quantity
0,CA-1001,John,South,Furniture,2500.0,200.0,0.10,2.0
1,CA-1002,NaN,East,Technology,NaN,350.0,NaN,3.0
2,CA-1003,David,NaN,Office Supplies,1800.0,NaN,0.20,NaN
3,CA-1004,Maria,West,NaN,3200.0,500.0,0.15,5.0

## axis=0 means it works on row level

In [14]:
df2.dropna(how='any',axis=0)

  Order_ID Customer_Name Region   Category   Sales  Profit  Discount  Quantity
0  CA-1001          John  South  Furniture  2500.0   200.0       0.1       2.0

In [15]:
df2.dropna(how='all',axis=0)

,Order_ID,Customer_Name,Region,Category,Sales,Profit,Discount,Quantity
0,CA-1001,John,South,Furniture,2500.0,200.0,0.10,2.0
1,CA-1002,NaN,East,Technology,NaN,350.0,NaN,3.0
2,CA-1003,David,NaN,Office Supplies,1800.0,NaN,0.20,NaN
3,CA-1004,Maria,West,NaN,3200.0,500.0,0.15,5.0

In [17]:
(df2.dropna(axis=1,thresh=len(df2)-2))

,Order_ID,Customer_Name,Region,Category,Sales,Profit,Discount,Quantity
0,CA-1001,John,South,Furniture,2500.0,200.0,0.10,2.0
1,CA-1002,NaN,East,Technology,NaN,350.0,NaN,3.0
2,CA-1003,David,NaN,Office Supplies,1800.0,NaN,0.20,NaN
3,CA-1004,Maria,West,NaN,3200.0,500.0,0.15,5.0

## Forward Fill:(ffill)

In [18]:
df2.ffill()

,Order_ID,Customer_Name,Region,Category,Sales,Profit,Discount,Quantity
0,CA-1001,John,South,Furniture,2500.0,200.0,0.10,2.0
1,CA-1002,John,East,Technology,2500.0,350.0,0.10,3.0
2,CA-1003,David,East,Office Supplies,1800.0,350.0,0.20,3.0
3,CA-1004,Maria,West,Office Supplies,3200.0,500.0,0.15,5.0

## Backward Fill

In [19]:
df2.bfill()

,Order_ID,Customer_Name,Region,Category,Sales,Profit,Discount,Quantity
0,CA-1001,John,South,Furniture,2500.0,200.0,0.10,2.0
1,CA-1002,David,East,Technology,1800.0,350.0,0.20,3.0
2,CA-1003,David,West,Office Supplies,1800.0,500.0,0.20,5.0
3,CA-1004,Maria,West,NaN,3200.0,500.0,0.15,5.0