In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("C:/Users/chand/OneDrive/Documents/Desktop/python_pandas/Superstore sales dataset.csv")

In [5]:
df.shape

(9994, 21)

In [6]:
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,8/11/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,8/11/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,12/6/2016,16/6/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,11/10/2015,18/10/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,11/10/2015,18/10/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,21/1/2014,23/1/2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,9991,CA-2017-121258,26/2/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,9992,CA-2017-121258,26/2/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,9993,CA-2017-121258,26/2/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,9994,CA-2017-119914,4/5/2017,9/5/2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

In [7]:
df.dtypes

Row ID             int64
Order ID          object
Order Date        object
Ship Date         object
Ship Mode         object
Customer ID       object
Customer Name     object
Segment           object
Country           object
City              object
State             object
Postal Code        int64
Region            object
Product ID        object
Category          object
Sub-Category      object
Product Name      object
Sales            float64
Quantity           int64
Discount         float64
Profit           float64
dtype: object

In [8]:
df['Order Date']=pd.to_datetime(df['Order Date'],dayfirst=True)

In [9]:
df['Ship Date']=pd.to_datetime(df['Ship Date'],dayfirst=True)

In [10]:
df['Order Date'].dt.day_name()

0        Tuesday
1        Tuesday
2         Sunday
3         Sunday
4         Sunday
          ...
9989     Tuesday
9990      Sunday
9991      Sunday
9992      Sunday
9993    Thursday
Name: Order Date, Length: 9994, dtype: object

In [11]:
df['Order Date'].dt.weekday

0       1
1       1
2       6
3       6
4       6
       ..
9989    1
9990    6
9991    6
9992    6
9993    3
Name: Order Date, Length: 9994, dtype: int32

In [12]:
df['Order Date'].dt.day_of_week

0       1
1       1
2       6
3       6
4       6
       ..
9989    1
9990    6
9991    6
9992    6
9993    3
Name: Order Date, Length: 9994, dtype: int32

# HOURS

In [13]:
df['Order Date'].dt.hour

0       0
1       0
2       0
3       0
4       0
       ..
9989    0
9990    0
9991    0
9992    0
9993    0
Name: Order Date, Length: 9994, dtype: int32

In [14]:
df['Order Date'].dt.minute

0       0
1       0
2       0
3       0
4       0
       ..
9989    0
9990    0
9991    0
9992    0
9993    0
Name: Order Date, Length: 9994, dtype: int32

In [15]:
df['Order Date'].dt.second

0       0
1       0
2       0
3       0
4       0
       ..
9989    0
9990    0
9991    0
9992    0
9993    0
Name: Order Date, Length: 9994, dtype: int32

In [16]:
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,2014-01-21,2014-01-23,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,9991,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,9992,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,9993,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,9994,CA-2017-119914,2017-05-04,2017-05-09,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

In [17]:
df['Customer Name'].str.upper()

0            CLAIRE GUTE
1            CLAIRE GUTE
2        DARRIN VAN HUFF
3         SEAN O'DONNELL
4         SEAN O'DONNELL
              ...
9989    TOM BOECKENHAUER
9990         DAVE BROOKS
9991         DAVE BROOKS
9992         DAVE BROOKS
9993        CHRIS CORTES
Name: Customer Name, Length: 9994, dtype: object

In [18]:
df['year']=df['Order Date'].dt.year

In [19]:
df['year']

0       2016
1       2016
2       2016
3       2015
4       2015
        ...
9989    2014
9990    2017
9991    2017
9992    2017
9993    2017
Name: year, Length: 9994, dtype: int32

In [20]:
df['Order Date'].dt.day

0        8
1        8
2       12
3       11
4       11
        ..
9989    21
9990    26
9991    26
9992    26
9993     4
Name: Order Date, Length: 9994, dtype: int32

In [21]:
df['Order Date'].dt.hour

0       0
1       0
2       0
3       0
4       0
       ..
9989    0
9990    0
9991    0
9992    0
9993    0
Name: Order Date, Length: 9994, dtype: int32

In [22]:
print(df['Order Date'].dt.day_name().head(4))
print(df['Order Date'].dt.month_name().head(4))

0    Tuesday
1    Tuesday
2     Sunday
3     Sunday
Name: Order Date, dtype: object
0    November
1    November
2        June
3     October
Name: Order Date, dtype: object

In [23]:
df['Order Date'].dt.quarter.head()

0    4
1    4
2    2
3    4
4    4
Name: Order Date, dtype: int32

In [24]:
df_sub=df.iloc[0:5,:]

In [25]:
df_sub['Order Date'].dt.dayofyear

0    313
1    313
2    164
3    284
4    284
Name: Order Date, dtype: int32

In [26]:
df_sub['Order Date'].dt.is_month_start

0    False
1    False
2    False
3    False
4    False
Name: Order Date, dtype: bool

In [27]:
df['Order Date'].dt.is_month_end

0       False
1       False
2       False
3       False
4       False
        ...
9989    False
9990    False
9991    False
9992    False
9993    False
Name: Order Date, Length: 9994, dtype: bool

In [28]:
df['Order Date'].dt.is_quarter_start

0       False
1       False
2       False
3       False
4       False
        ...
9989    False
9990    False
9991    False
9992    False
9993    False
Name: Order Date, Length: 9994, dtype: bool

In [29]:
df['Order Date'].dt.is_quarter_end

0       False
1       False
2       False
3       False
4       False
        ...
9989    False
9990    False
9991    False
9992    False
9993    False
Name: Order Date, Length: 9994, dtype: bool

In [30]:
df['Order Date'].dt.is_year_start

0       False
1       False
2       False
3       False
4       False
        ...
9989    False
9990    False
9991    False
9992    False
9993    False
Name: Order Date, Length: 9994, dtype: bool

In [31]:
df['Order Date'].dt.is_year_end

0       False
1       False
2       False
3       False
4       False
        ...
9989    False
9990    False
9991    False
9992    False
9993    False
Name: Order Date, Length: 9994, dtype: bool

In [32]:
(df['Ship Date']-df['Order Date']).max()

Timedelta('7 days 00:00:00')

In [33]:
(df['Ship Date']-df['Order Date']).min()

Timedelta('0 days 00:00:00')

In [34]:
(df['Ship Date']-df['Order Date']).mean()

Timedelta('3 days 22:59:46.311787072')

In [35]:
(df['Ship Date']-df['Order Date']).median()

Timedelta('4 days 00:00:00')

In [36]:
df[(df['Ship Date']-df['Order Date']).dt.days>6]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,year
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,2015
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,2015
16,17,CA-2014-105893,2014-11-11,2014-11-18,Standard Class,PK-19075,Pete Kriz,Consumer,United States,Madison,...,Central,OFF-ST-10004186,Office Supplies,Storage,"Stur-D-Stor Shelving, Vertical 5-Shelf: 72""H x...",665.8800,6,0.00,13.3176,2014
86,87,CA-2017-155558,2017-10-26,2017-11-02,Standard Class,PG-18895,Paul Gonzalez,Consumer,United States,Rochester,...,Central,TEC-AC-10001998,Technology,Accessories,Logitech LS21 Speaker System - PC Multimedia -...,19.9900,1,0.00,6.7966,2017
87,88,CA-2017-155558,2017-10-26,2017-11-02,Standard Class,PG-18895,Paul Gonzalez,Consumer,United States,Rochester,...,Central,OFF-LA-10000134,Office Supplies,Labels,Avery 511,6.1600,2,0.00,2.9568,2017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9801,9802,CA-2017-137918,2017-09-29,2017-10-06,Standard Class,JK-15730,Joe Kamberova,Consumer,United States,Lodi,...,West,OFF-SU-10000898,Office Supplies,Supplies,Acme Hot Forged Carbon Steel Scissors with Nic...,97.3000,7,0.00,28.2170,2017
9827,9828,CA-2017-169999,2017-06-19,2017-06-26,Standard Class,JS-15685,Jim Sink,Corporate,United States,New York City,...,East,OFF-ST-10001511,Office Supplies,Storage,Space Solutions Commercial Steel Shelving,129.3000,2,0.00,6.4650,2017
9828,9829,CA-2017-169999,2017-06-19,2017-06-26,Standard Class,JS-15685,Jim Sink,Corporate,United States,New York City,...,East,OFF-BI-10004728,Office Supplies,Binders,Wilson Jones Turn Tabs Binder Tool for Ring Bi...,11.5680,3,0.20,3.7596,2017
9829,9830,US-2017-152842,2017-07-16,2017-07-23,Standard Class,NF-18385,Natalie Fritzler,Consumer,United States,Charlotte,...,South,FUR-CH-10004218,Furniture,Chairs,"Global Fabric Manager's Chair, Dark Gray",242.3520,3,0.20,15.1470,2017
9875,9876,CA-2015-130855,2015-12-29,2016-01-05,Standard Class,RF-19840,Roy Französisch,Consumer,United States,New York City,...,East,OFF-SU-10003936,Office Supplies,Supplies,Acme Serrated Blade Letter Opener,6.3600,2,0.00,0.0636,2015

In [37]:
df.shape

(9994, 22)

In [38]:
### late_shipping
### ship date and order date>5

df[(df['Ship Date']-df['Order Date']).dt.days>5].shape

(1824, 22)

In [39]:
df[df['Order Date'].dt.day_name()=='wednesday'].shape

(0, 22)

In [40]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit', 'year'],
      dtype='object')

In [41]:
df['Region'].nunique()

4

In [42]:
df.shape

(9994, 22)

In [43]:
df.nunique()

Row ID           9994
Order ID         5009
Order Date       1237
Ship Date        1334
Ship Mode           4
Customer ID       793
Customer Name     793
Segment             3
Country             1
City              531
State              49
Postal Code       631
Region              4
Product ID       1862
Category            3
Sub-Category       17
Product Name     1850
Sales            5825
Quantity           14
Discount           12
Profit           7287
year                4
dtype: int64

In [44]:
df['City'].nunique()

531

In [45]:
df['Region'].value_counts()

Region
West       3203
East       2848
Central    2323
South      1620
Name: count, dtype: int64

In [46]:
(df['Region'].value_counts(normalize=True))*100

Region
West       32.049230
East       28.497098
Central    23.243946
South      16.209726
Name: proportion, dtype: float64

In [47]:
df.describe()

,Row ID,Order Date,Ship Date,Postal Code,Sales,Quantity,Discount,Profit,year
count,9994.000000,9994,9994,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,2016-04-30 00:07:12.259355648,2016-05-03 23:06:58.571142912,55190.379428,229.858001,3.789574,0.156203,28.656896,2015.722233
min,1.000000,2014-01-03 00:00:00,2014-01-07 00:00:00,1040.000000,0.444000,1.000000,0.000000,-6599.978000,2014.000000
25%,2499.250000,2015-05-23 00:00:00,2015-05-27 00:00:00,23223.000000,17.280000,2.000000,0.000000,1.728750,2015.000000
50%,4997.500000,2016-06-26 00:00:00,2016-06-29 00:00:00,56430.500000,54.490000,3.000000,0.200000,8.666500,2016.000000
75%,7495.750000,2017-05-14 00:00:00,2017-05-18 00:00:00,90008.000000,209.940000,5.000000,0.200000,29.364000,2017.000000
max,9994.000000,2017-12-30 00:00:00,2018-01-05 00:00:00,99301.000000,22638.480000,14.000000,0.800000,8399.976000,2017.000000
std,2885.163629,NaN,NaN,32063.693350,623.245101,2.225110,0.206452,234.260108,1.123555

In [48]:
df.describe(include='object')

,Order ID,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Region,Product ID,Category,Sub-Category,Product Name
count,9994,9994,9994,9994,9994,9994,9994,9994,9994,9994,9994,9994,9994
unique,5009,4,793,793,3,1,531,49,4,1862,3,17,1850
top,CA-2017-100111,Standard Class,WB-21850,William Brown,Consumer,United States,New York City,California,West,OFF-PA-10001970,Office Supplies,Binders,Staple envelope
freq,14,5968,37,37,5191,9994,915,2001,3203,19,6026,1523,48

In [53]:
df['sales']=pd.cut(df['Sales'],bins=[0,5000,10000,15000,20000],labels=['low','medium','high','very high'])

In [54]:
df['sales']

0       low
1       low
2       low
3       low
4       low
       ...
9989    low
9990    low
9991    low
9992    low
9993    low
Name: sales, Length: 9994, dtype: category
Categories (4, object): ['low' < 'medium' < 'high' < 'very high']

In [55]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit', 'year',
       'sales'],
      dtype='object')

In [56]:
for i in df.columns:
    if df[i].nunique()<6:
        print(i)

Ship Mode
Segment
Country
Region
Category
year
sales

In [60]:
df.groupby(['Ship Mode','year'])[['Sales','Profit']].sum()

                           Sales      Profit
Ship Mode      year
First Class    2014   59769.2645   9073.5332
               2015   69259.4390  10146.4402
               2016   82265.3428   9355.8487
               2017  140134.3766  20394.0178
Same Day       2014   17470.1340   2755.5071
               2015   27611.4900   4327.4275
               2016   34505.7610   5440.4492
               2017   48775.7400   3368.3751
Second Class   2014  101386.7800   9759.4570
               2015   89102.7254  10751.1519
               2016  120002.4406  16346.7570
               2017  148701.6234  20589.2695
Standard Class 2014  305621.3196  27955.4768
               2015  284558.8546  36393.5841
               2016  372432.0536  50652.1194
               2017  395603.5152  49087.6072