# Hands-on Pandas Notebook

This notebook will guide you through various essential Pandas functions using dummy data. Pandas is a powerful open-source data analysis and manipulation tool, built on top of the Python programming language.

# 1. import pandas and creating dataframes

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = {
    'Name': ['chandu', 'aravind', 'suku', 'malli', 'trivi'],
    'Age': [24, 27, 22, 32, 29],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix'],
    'Occupation': ['Engineer', 'Doctor', 'Artist', 'Scientist', 'Teacher']
}
df = pd.DataFrame(data)

In [3]:
df

      Name  Age         City Occupation
0   chandu   24     New York   Engineer
1  aravind   27  Los Angeles     Doctor
2     suku   22      Chicago     Artist
3    malli   32      Houston  Scientist
4    trivi   29      Phoenix    Teacher

creating a dataframe from a list of lists(with columns)

In [4]:
data_list = [
        ['jagan',23,'jagadamba'],
        ['surya',24,'pendhurthi'],
        ['hemanth',25,'sabbavarm']
]
columns_list = ['Name','Age','City']
df_list = pd.DataFrame(data_list,columns=columns_list)

In [5]:
df_list

      Name  Age        City
0    jagan   23   jagadamba
1    surya   24  pendhurthi
2  hemanth   25   sabbavarm

creating a dataframe from numpy array

In [6]:
data_np = np.array([[10,20,30],[40,50,60],[70,80,90]])
df_np = pd.DataFrame(data_np,columns=['clo1','col2','col3'])

In [7]:
df_np

   clo1  col2  col3
0    10    20    30
1    40    50    60
2    70    80    90

# 2.basic dataframe operations

In [8]:
print('### displaying data')
print("first 3 rows (head):")
df.head(3)

### displaying data
first 3 rows (head):

      Name  Age         City Occupation
0   chandu   24     New York   Engineer
1  aravind   27  Los Angeles     Doctor
2     suku   22      Chicago     Artist

In [9]:
print("last 2 rows (tail):")
df.tail(2)

last 2 rows (tail):

    Name  Age     City Occupation
3  malli   32  Houston  Scientist
4  trivi   29  Phoenix    Teacher

In [10]:
print("DataFrame Info (data types, non-null counts):")
df.info()

DataFrame Info (data types, non-null counts):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        5 non-null      object
 1   Age         5 non-null      int64
 2   City        5 non-null      object
 3   Occupation  5 non-null      object
dtypes: int64(1), object(3)
memory usage: 292.0+ bytes

In [11]:
print("Descriptive Statistics (for numerical columns):")
display(df.describe())

Descriptive Statistics (for numerical columns):

             Age
count   5.000000
mean   26.800000
std     3.962323
min    22.000000
25%    24.000000
50%    27.000000
75%    29.000000
max    32.000000

selecting columns

In [12]:
# selecting a single columns

df['Name']

0     chandu
1    aravind
2       suku
3      malli
4      trivi
Name: Name, dtype: object

In [13]:
# selecting a multiple columns

df[['Name','Age']]

      Name  Age
0   chandu   24
1  aravind   27
2     suku   22
3    malli   32
4    trivi   29

adding and modifying columns

In [14]:
# add a new column

df['salary'] = [70000,85000,60000,95000,78000]

In [15]:
df

      Name  Age         City Occupation  salary
0   chandu   24     New York   Engineer   70000
1  aravind   27  Los Angeles     Doctor   85000
2     suku   22      Chicago     Artist   60000
3    malli   32      Houston  Scientist   95000
4    trivi   29      Phoenix    Teacher   78000

In [16]:
# modying an existing column

df['Age'] = df['Age'] + 1

In [17]:
df['Age']

0    25
1    28
2    23
3    33
4    30
Name: Age, dtype: int64

In [18]:
# Adding a column based on existing ones

df['Age_Category'] = pd.cut(df['Age'],bins=[0,25,30,100],labels = ['Young','Adult','Senior'])

In [19]:
df['Age_Category']

0     Young
1     Adult
2     Young
3    Senior
4     Adult
Name: Age_Category, dtype: category
Categories (3, object): ['Young' < 'Adult' < 'Senior']

In [20]:
df

      Name  Age         City Occupation  salary Age_Category
0   chandu   25     New York   Engineer   70000        Young
1  aravind   28  Los Angeles     Doctor   85000        Adult
2     suku   23      Chicago     Artist   60000        Young
3    malli   33      Houston  Scientist   95000       Senior
4    trivi   30      Phoenix    Teacher   78000        Adult

Filtering rows

In [21]:
# filter rows where age > 25

df[df['Age'] > 25]

      Name  Age         City Occupation  salary Age_Category
1  aravind   28  Los Angeles     Doctor   85000        Adult
3    malli   33      Houston  Scientist   95000       Senior
4    trivi   30      Phoenix    Teacher   78000        Adult

In [22]:
# Filter rows for a specific city

df[df['City'] == 'New York']

     Name  Age      City Occupation  salary Age_Category
0  chandu   25  New York   Engineer   70000        Young

In [23]:
# Filter rows with multiple conditions

df[(df['Age'] > 25) & (df['City'] == 'Los Angles')]

Empty DataFrame
Columns: [Name, Age, City, Occupation, salary, Age_Category]
Index: []

# 3. Handling Missing Data

In [24]:
df

      Name  Age         City Occupation  salary Age_Category
0   chandu   25     New York   Engineer   70000        Young
1  aravind   28  Los Angeles     Doctor   85000        Adult
2     suku   23      Chicago     Artist   60000        Young
3    malli   33      Houston  Scientist   95000       Senior
4    trivi   30      Phoenix    Teacher   78000        Adult

In [25]:
df_missing = df.copy()
df_missing.loc[1, 'Age'] = np.nan # Introduce a missing value
df_missing.loc[3, 'Occupation'] = np.nan # Introduce another missing value
df_missing.loc[0, 'salary'] = np.nan # Another missing value

In [26]:
df_missing

      Name   Age         City Occupation   salary Age_Category
0   chandu  25.0     New York   Engineer      NaN        Young
1  aravind   NaN  Los Angeles     Doctor  85000.0        Adult
2     suku  23.0      Chicago     Artist  60000.0        Young
3    malli  33.0      Houston        NaN  95000.0       Senior
4    trivi  30.0      Phoenix    Teacher  78000.0        Adult

In [27]:
# print("DataFrame with introduced missing values:")

df_missing

      Name   Age         City Occupation   salary Age_Category
0   chandu  25.0     New York   Engineer      NaN        Young
1  aravind   NaN  Los Angeles     Doctor  85000.0        Adult
2     suku  23.0      Chicago     Artist  60000.0        Young
3    malli  33.0      Houston        NaN  95000.0       Senior
4    trivi  30.0      Phoenix    Teacher  78000.0        Adult

In [28]:
# identify missing values

df_missing.isnull()

    Name    Age   City  Occupation  salary  Age_Category
0  False  False  False       False    True         False
1  False   True  False       False   False         False
2  False  False  False       False   False         False
3  False  False  False        True   False         False
4  False  False  False       False   False         False

In [29]:
# print("df.isnull().sum() (count of missing values per column):")

df_missing.isnull().sum() # checking column wise null values

Name            0
Age             1
City            0
Occupation      1
salary          1
Age_Category    0
dtype: int64

Filling missing null values

In [30]:
# fill missing 'Age' with the mean age

df_fill_mean = df_missing.copy()

In [31]:
df_fill_mean

      Name   Age         City Occupation   salary Age_Category
0   chandu  25.0     New York   Engineer      NaN        Young
1  aravind   NaN  Los Angeles     Doctor  85000.0        Adult
2     suku  23.0      Chicago     Artist  60000.0        Young
3    malli  33.0      Houston        NaN  95000.0       Senior
4    trivi  30.0      Phoenix    Teacher  78000.0        Adult

In [32]:
df_fill_mean = df_missing.copy()
df_fill_mean['Age'] = df_fill_mean['Age'].fillna(df_fill_mean['Age'].mean())

In [33]:
df_fill_mean

      Name    Age         City Occupation   salary Age_Category
0   chandu  25.00     New York   Engineer      NaN        Young
1  aravind  27.75  Los Angeles     Doctor  85000.0        Adult
2     suku  23.00      Chicago     Artist  60000.0        Young
3    malli  33.00      Houston        NaN  95000.0       Senior
4    trivi  30.00      Phoenix    Teacher  78000.0        Adult

In [34]:
# filling occupation with a specific value

df_fill_value = df_missing.copy()

In [35]:
df_fill_value

      Name   Age         City Occupation   salary Age_Category
0   chandu  25.0     New York   Engineer      NaN        Young
1  aravind   NaN  Los Angeles     Doctor  85000.0        Adult
2     suku  23.0      Chicago     Artist  60000.0        Young
3    malli  33.0      Houston        NaN  95000.0       Senior
4    trivi  30.0      Phoenix    Teacher  78000.0        Adult

In [36]:
df_fill_value['Occupation'] = df_fill_value['Occupation'].fillna('unknown')

In [37]:
df_fill_value

      Name   Age         City Occupation   salary Age_Category
0   chandu  25.0     New York   Engineer      NaN        Young
1  aravind   NaN  Los Angeles     Doctor  85000.0        Adult
2     suku  23.0      Chicago     Artist  60000.0        Young
3    malli  33.0      Houston    unknown  95000.0       Senior
4    trivi  30.0      Phoenix    Teacher  78000.0        Adult

Dropping missing values

In [38]:
# drop rows with any missing values

df_dropped_rows = df_missing.dropna()

In [39]:
df_dropped_rows

    Name   Age     City Occupation   salary Age_Category
2   suku  23.0  Chicago     Artist  60000.0        Young
4  trivi  30.0  Phoenix    Teacher  78000.0        Adult

In [40]:
# Drop columns with any missing values

df_dropped_cols = df_missing.dropna(axis = 1)

In [41]:
df_dropped_cols

      Name         City Age_Category
0   chandu     New York        Young
1  aravind  Los Angeles        Adult
2     suku      Chicago        Young
3    malli      Houston       Senior
4    trivi      Phoenix        Adult

In [42]:
df_dropped_rows = df_missing.dropna(axis = 0)
df_dropped_rows

    Name   Age     City Occupation   salary Age_Category
2   suku  23.0  Chicago     Artist  60000.0        Young
4  trivi  30.0  Phoenix    Teacher  78000.0        Adult

category : grouping and aggregations

In [43]:
# Create a DataFrame for grouping examples

df_sales_data = pd.DataFrame({
    'Region': ['East', 'West', 'East', 'West', 'East', 'West'],
    'Product': ['A', 'B', 'A', 'C', 'B', 'A'],
    'Sales': [100, 150, 120, 200, 130, 110],
    'Units': [10, 15, 12, 20, 13, 11]
})

In [44]:
df_sales_data

  Region Product  Sales  Units
0   East       A    100     10
1   West       B    150     15
2   East       A    120     12
3   West       C    200     20
4   East       B    130     13
5   West       A    110     11

#### Function: `.groupby().mean()` (Basic aggregation)

In [45]:
# mean sales by region

df_sales_data.groupby('Region')['Sales'].mean()

Region
East    116.666667
West    153.333333
Name: Sales, dtype: float64

#### Function: .groupby().agg() (Multiple aggregations)

In [46]:
# print("Sales statistics (sum, mean, max) by Region and Product:")

df_sales_data.groupby(['Region','Product'])['Sales'].agg(['sum','mean','max'])

                sum   mean  max
Region Product
East   A        220  110.0  120
       B        130  130.0  130
West   A        110  110.0  110
       B        150  150.0  150
       C        200  200.0  200

#### Function: .value_counts() (Counting unique values)

In [47]:
# print("Count of each Product sold:")

df_sales_data['Product'].value_counts()

Product
A    3
B    2
C    1
Name: count, dtype: int64

#### Category: Merging and Joining DataFrames

In [48]:
# Create two DataFrames for merging examples


df_employees = pd.DataFrame({
    'EmpID': [1, 2, 3, 4],
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Department': ['HR', 'IT', 'Finance', 'HR']
})
df_salaries = pd.DataFrame({
    'EmpID': [1, 2, 3, 5],
    'Salary': [70000, 80000, 60000, 90000]
})
# print("df_employees:")
# display(df_employees)
# print("df_salaries:")
# display(df_salaries)

In [49]:
df_employees

   EmpID     Name Department
0      1    Alice         HR
1      2      Bob         IT
2      3  Charlie    Finance
3      4    David         HR

In [50]:
df_salaries

   EmpID  Salary
0      1   70000
1      2   80000
2      3   60000
3      5   90000

#### Function: pd.merge() (Inner Join - default)

In [51]:
# print("Inner join of employees and salaries on 'EmpID' (only matching IDs):")

df_merged = pd.merge(df_employees,df_salaries,on='EmpID',how='inner')

In [52]:
df_merged

   EmpID     Name Department  Salary
0      1    Alice         HR   70000
1      2      Bob         IT   80000
2      3  Charlie    Finance   60000

#### Function: pd.merge(how='left') (Left Join)

In [53]:
pd.merge(df_employees,df_salaries,on='EmpID',how='left')

   EmpID     Name Department   Salary
0      1    Alice         HR  70000.0
1      2      Bob         IT  80000.0
2      3  Charlie    Finance  60000.0
3      4    David         HR      NaN

#### Function: pd.concat() (Concatenating DataFrames)

In [54]:
df_new_employees = pd.DataFrame({
    'EmpID': [5, 6],
    'Name': ['Eve', 'Frank'],
    'Department': ['IT', 'Marketing']
})

In [55]:
pd.concat([df_employees,df_new_employees],ignore_index=True)

   EmpID     Name Department
0      1    Alice         HR
1      2      Bob         IT
2      3  Charlie    Finance
3      4    David         HR
4      5      Eve         IT
5      6    Frank  Marketing

#### Category: Pivoting and Reshaping Data

In [56]:
# Create a DataFrame for pivoting examples


df_pivot_data = pd.DataFrame({
    'Date': ['2023-01-01', '2023-01-01', '2023-01-02', '2023-01-02'],
    'City': ['NY', 'LA', 'NY', 'LA'],
    'Product': ['A', 'B', 'A', 'C'],
    'Sales': [100, 150, 120, 200]
})

In [57]:
df_pivot_data

         Date City Product  Sales
0  2023-01-01   NY       A    100
1  2023-01-01   LA       B    150
2  2023-01-02   NY       A    120
3  2023-01-02   LA       C    200

In [58]:
# print("Total Sales by City for each Product using pivot_table:")

display(df_pivot_data.pivot_table(values='Sales', index='City', columns='Product', aggfunc='sum'))

Product      A      B      C
City
LA         NaN  150.0  200.0
NY       220.0    NaN    NaN

In [59]:
df_pivot_data.pivot_table(values='Sales',index='Date',columns='Product',aggfunc='sum')

Product         A      B      C
Date
2023-01-01  100.0  150.0    NaN
2023-01-02  120.0    NaN  200.0

In [60]:
df_pivot_data

         Date City Product  Sales
0  2023-01-01   NY       A    100
1  2023-01-01   LA       B    150
2  2023-01-02   NY       A    120
3  2023-01-02   LA       C    200

#### Function : .stack() and .unstack()

In [61]:
df_stack_unstack = df_pivot_data.set_index(['Date','City','Product'])

# print("Multi-indexed DataFrame:")

df_stack_unstack

                         Sales
Date       City Product
2023-01-01 NY   A          100
           LA   B          150
2023-01-02 NY   A          120
           LA   C          200

In [62]:
df_stack_unstack.stack()

Date        City  Product
2023-01-01  NY    A        Sales    100
            LA    B        Sales    150
2023-01-02  NY    A        Sales    120
            LA    C        Sales    200
dtype: int64

In [63]:
df_stack_unstack.unstack(level='Product')

                 Sales
Product              A      B      C
Date       City
2023-01-01 LA      NaN  150.0    NaN
           NY    100.0    NaN    NaN
2023-01-02 LA      NaN    NaN  200.0
           NY    120.0    NaN    NaN

# 4. Grouping and Aggregating Data

In [64]:
# print("### Grouping by a Column and Calculating Mean")

# Let's recreate our initial df for clearer grouping examples

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Heidi'],
    'Age': [24, 27, 22, 32, 29, 24, 32, 27],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'New York', 'Los Angeles', 'Chicago'],
    'Occupation': ['Engineer', 'Doctor', 'Artist', 'Scientist', 'Teacher', 'Engineer', 'Scientist', 'Artist'],
    'Salary': [70000, 85000, 60000, 95000, 78000, 72000, 98000, 62000]
}

In [65]:
df = pd.DataFrame(data)

In [66]:
df

      Name  Age         City Occupation  Salary
0    Alice   24     New York   Engineer   70000
1      Bob   27  Los Angeles     Doctor   85000
2  Charlie   22      Chicago     Artist   60000
3    David   32      Houston  Scientist   95000
4      Eve   29      Phoenix    Teacher   78000
5    Frank   24     New York   Engineer   72000
6    Grace   32  Los Angeles  Scientist   98000
7    Heidi   27      Chicago     Artist   62000

In [67]:
# print("Mean Salary by City:")

df.groupby('City')['Salary'].mean()

City
Chicago        61000.0
Houston        95000.0
Los Angeles    91500.0
New York       71000.0
Phoenix        78000.0
Name: Salary, dtype: float64

In [68]:
# print("Mean Age and Salary by Occupation:")

df.groupby('Occupation')[['Age','Salary']].mean()

             Age   Salary
Occupation
Artist      24.5  61000.0
Doctor      27.0  85000.0
Engineer    24.0  71000.0
Scientist   32.0  96500.0
Teacher     29.0  78000.0

In [69]:
# print("### Aggregating Multiple Functions")

# print("Aggregating count, mean, and max salary by City:")

df.groupby('City')['Salary'].agg(['count','mean','max'])

             count     mean    max
City
Chicago          2  61000.0  62000
Houston          1  95000.0  95000
Los Angeles      2  91500.0  98000
New York         2  71000.0  72000
Phoenix          1  78000.0  78000

In [70]:
# print("### Value Counts")

# print("Count of each Occupation:")

df['Occupation'].value_counts()

Occupation
Engineer     2
Artist       2
Scientist    2
Doctor       1
Teacher      1
Name: count, dtype: int64

# 5. Merging and Joining DataFrames

In [71]:
df_employees = pd.DataFrame({
    'ID': [1, 2, 3, 4, 5],
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Department': ['HR', 'IT', 'Finance', 'IT', 'HR']
})

df_salaries = pd.DataFrame({
    'ID': [1, 2, 3, 4, 6],
    'Salary': [70000, 85000, 60000, 95000, 78000]
})

df_projects = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'Grace'],
    'Project': ['Alpha', 'Beta', 'Gamma', 'Delta']
})

In [72]:
df_employees

   ID     Name Department
0   1    Alice         HR
1   2      Bob         IT
2   3  Charlie    Finance
3   4    David         IT
4   5      Eve         HR

In [73]:
df_salaries

   ID  Salary
0   1   70000
1   2   85000
2   3   60000
3   4   95000
4   6   78000

In [74]:
df_projects

      Name Project
0    Alice   Alpha
1      Bob    Beta
2  Charlie   Gamma
3    Grace   Delta

In [75]:
# print("### Inner Merge (default)")

# print("Merging employees and salaries on 'ID' (inner join - common IDs only):")

pd.merge(df_employees,df_salaries,on='ID')

   ID     Name Department  Salary
0   1    Alice         HR   70000
1   2      Bob         IT   85000
2   3  Charlie    Finance   60000
3   4    David         IT   95000

In [76]:
# print("### Left Merge")
# print("Merging employees and salaries on 'ID' (left join - keep all employees):")

pd.merge(df_employees,df_salaries,on='ID',how='left')

   ID     Name Department   Salary
0   1    Alice         HR  70000.0
1   2      Bob         IT  85000.0
2   3  Charlie    Finance  60000.0
3   4    David         IT  95000.0
4   5      Eve         HR      NaN

In [77]:
df_employees

   ID     Name Department
0   1    Alice         HR
1   2      Bob         IT
2   3  Charlie    Finance
3   4    David         IT
4   5      Eve         HR

In [78]:
df_salaries

   ID  Salary
0   1   70000
1   2   85000
2   3   60000
3   4   95000
4   6   78000

In [79]:
# print("### Right Merge")
# print("Merging employees and salaries on 'ID' (right join - keep all salaries):")

pd.merge(df_employees,df_salaries,on='ID',how='right')

   ID     Name Department  Salary
0   1    Alice         HR   70000
1   2      Bob         IT   85000
2   3  Charlie    Finance   60000
3   4    David         IT   95000
4   6      NaN        NaN   78000

In [80]:
# print("### Outer Merge")
# print("Merging employees and salaries on 'ID' (outer join - keep all records):")

pd.merge(df_employees,df_salaries,on='ID',how='outer')

   ID     Name Department   Salary
0   1    Alice         HR  70000.0
1   2      Bob         IT  85000.0
2   3  Charlie    Finance  60000.0
3   4    David         IT  95000.0
4   5      Eve         HR      NaN
5   6      NaN        NaN  78000.0

In [81]:
# print("### Merging on different column names")
# # Merging df_employees and df_projects where employee 'Name' matches project 'Name'
# print("Merging employees and projects on 'Name' (employees.Name = projects.Name):")

pd.merge(df_employees,df_projects,left_on='Name',right_on='Name',how='inner')

   ID     Name Department Project
0   1    Alice         HR   Alpha
1   2      Bob         IT    Beta
2   3  Charlie    Finance   Gamma

In [82]:
# print("### Concatenating DataFrames")
# Vertically concatenate

df_more_employees = pd.DataFrame({
    'ID': [7, 8],
    'Name': ['Victor', 'Wendy'],
    'Department': ['IT', 'HR']
})

In [83]:
pd.concat([df_employees,df_more_employees], ignore_index=True)

   ID     Name Department
0   1    Alice         HR
1   2      Bob         IT
2   3  Charlie    Finance
3   4    David         IT
4   5      Eve         HR
5   7   Victor         IT
6   8    Wendy         HR

In [84]:
# Horizontally concatenate (requires same index or join logic)

df_employee_contacts = pd.DataFrame({
    'Email': ['alice@example.com', 'bob@example.com', 'charlie@example.com', 'david@example.com', 'eve@example.com']
}, index=df_employees.index)

In [85]:
df_employee_contacts

                 Email
0    alice@example.com
1      bob@example.com
2  charlie@example.com
3    david@example.com
4      eve@example.com

In [86]:
pd.concat([df_employees,df_employee_contacts],axis=1)

   ID     Name Department                Email
0   1    Alice         HR    alice@example.com
1   2      Bob         IT      bob@example.com
2   3  Charlie    Finance  charlie@example.com
3   4    David         IT    david@example.com
4   5      Eve         HR      eve@example.com

# 6. Pivoting and Reshaping Data

In [87]:
df_sales = pd.DataFrame({
    'Date': ['2023-01-01', '2023-01-01', '2023-01-02', '2023-01-02', '2023-01-03'],
    'Region': ['East', 'West', 'East', 'West', 'East'],
    'Product': ['A', 'B', 'A', 'C', 'B'],
    'Sales': [100, 150, 120, 200, 130]
})

In [88]:
df_sales

         Date Region Product  Sales
0  2023-01-01   East       A    100
1  2023-01-01   West       B    150
2  2023-01-02   East       A    120
3  2023-01-02   West       C    200
4  2023-01-03   East       B    130

In [89]:
# print("### Pivot Table")
# # Pivot table to see total sales by Region for each Product
# print("Total Sales by Region and Product (using pivot_table):")

df_sales.pivot_table(values='Sales',index='Region',columns='Product',aggfunc='sum')

Product      A      B      C
Region
East     220.0  130.0    NaN
West       NaN  150.0  200.0

In [90]:
# print("### Stack and Unstack")
# # Create a multi-index DataFrame for stacking/unstacking

df_multi_index = df_sales.set_index(['Date','Region','Product'])

In [91]:
df_multi_index

                           Sales
Date       Region Product
2023-01-01 East   A          100
           West   B          150
2023-01-02 East   A          120
           West   C          200
2023-01-03 East   B          130

In [92]:
df_sales

         Date Region Product  Sales
0  2023-01-01   East       A    100
1  2023-01-01   West       B    150
2  2023-01-02   East       A    120
3  2023-01-02   West       C    200
4  2023-01-03   East       B    130

In [93]:

# Stack: Converts columns into rows, creating a MultiIndex
# print("Stacked DataFrame:")

display(df_multi_index.stack())

Date        Region  Product
2023-01-01  East    A        Sales    100
            West    B        Sales    150
2023-01-02  East    A        Sales    120
            West    C        Sales    200
2023-01-03  East    B        Sales    130
dtype: int64

In [94]:
#  Unstack: Converts rows into columns
# print("Unstacked DataFrame (from 'Product' level):")

display(df_multi_index.unstack(level='Product'))

                   Sales
Product                A      B      C
Date       Region
2023-01-01 East    100.0    NaN    NaN
           West      NaN  150.0    NaN
2023-01-02 East    120.0    NaN    NaN
           West      NaN    NaN  200.0
2023-01-03 East      NaN  130.0    NaN

#### Category: Time Series Functionality

#### Function: `pd.to_datetime()` and `.set_index()`

In [95]:
df_time_data = pd.DataFrame({
    'Date': ['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04'],
    'Value': [10, 12, 15, 11]
})

In [96]:
df_time_data['Date'] = pd.DataFrame(df_time_data['Date'])

In [97]:
df_time_data['Date']

0    2023-01-01
1    2023-01-02
2    2023-01-03
3    2023-01-04
Name: Date, dtype: object

In [98]:
df_time_indexed = df_time_data.set_index('Date')

In [99]:
df_time_indexed

            Value
Date
2023-01-01     10
2023-01-02     12
2023-01-03     15
2023-01-04     11

In [100]:
# print("DataFrame with DatetimeIndex:")

display(df_time_indexed)

            Value
Date
2023-01-01     10
2023-01-02     12
2023-01-03     15
2023-01-04     11

#### Function: .resample()

#### Function: Time-based selection with .loc[]

In [101]:
# print("Data for a specific date (2023-01-02):")

df_time_indexed.loc['2023-01-01']

Value    10
Name: 2023-01-01, dtype: int64

In [102]:
df_time_indexed.loc['2023-01-02']

Value    12
Name: 2023-01-02, dtype: int64

#### Category: Applying Functions

#### Function: .apply() on a Series

In [104]:
df_apply_data = pd.DataFrame({
    'Number': [1, 2, 3, 4, 5],
    'Text': ['apple', 'banana', 'cherry', 'date', 'elderberry']
})

In [105]:
df_apply_data

   Number        Text
0       1       apple
1       2      banana
2       3      cherry
3       4        date
4       5  elderberry

In [106]:

# df_apply_data['Number_Squared'] = df_apply_data['Number'].apply(lambda x: x**2)
# print("Column 'Number_Squared' using .apply() on Series:")
# display(df_apply_data)

df_apply_data['Number_squared'] = df_apply_data['Number'].apply(lambda x : x**2)

In [107]:
df_apply_data['Number_squared']

0     1
1     4
2     9
3    16
4    25
Name: Number_squared, dtype: int64

#### Function: .apply() on DataFrame (axis=1)

In [108]:
def combine_text_and_number(row):
    return f"{row['Text'].capitalize()}: {row['Number']}"

In [109]:
df_apply_data['Combined'] = df_apply_data.apply(combine_text_and_number,axis=1)

In [110]:
df_apply_data

   Number        Text  Number_squared       Combined
0       1       apple               1       Apple: 1
1       2      banana               4      Banana: 2
2       3      cherry               9      Cherry: 3
3       4        date              16        Date: 4
4       5  elderberry              25  Elderberry: 5

In [111]:
df_apply_data['Combined']

0         Apple: 1
1        Banana: 2
2        Cherry: 3
3          Date: 4
4    Elderberry: 5
Name: Combined, dtype: object

#### Function: .map()

In [ ]:
# status_map = {1: 'Low', 2: 'Medium', 3: 'Medium', 4: 'High', 5: 'High'}
# df_apply_data['Status'] = df_apply_data['Number'].map(status_map)
# print("Column 'Status' using .map():")
# display(df_apply_data)

df_apply_data['Status'] = df_apply_data['Number'].map(status_map)

NameError: name 'status_map' is not defined